name: SSDLC Actions

on:
  push:
    branches: ["main"] # Uses default branch
  pull_request:
    branches: ["main"] # Uses default branch

permissions: {}

jobs:
  code-security-analysis:
    permissions:
      contents: read
      actions: read
    uses: mozilla/ssdlc-actions/.github/workflows/code-security-analysis-private-repo.yml@ca8be48f3c06204fb16a3bd5ffa6d916782bbc76 # v1
